# Generated by Django 4.2.7 on 2023-12-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_post_author_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
    ]
