# Generated by Django 4.2.7 on 2023-12-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_remove_category_name_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.category'),
        ),
    ]
